trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: BuildPipelineVariables
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfigurationRelease
  value: 'Release'
- name: buildConfigurationSideload
  value: 'Sideload'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'

jobs:
### Sideload release ###
- job: SideloadRelease
  timeoutInMinutes: 40

  steps:
  - checkout: self
    submodules: true
  
  - task: PowerShell@2
    displayName: 'Canonicalize package manifest'
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\FluentHub.Uwp\Package.appxmanifest
        $xmlDoc.Package.Identity.Name="FluentHubDev"
        $xmlDoc.Package.Identity.Publisher="FluentHub Team"
        $xmlDoc.Package.Properties.DisplayName="FluentHub Dev"
        $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="FluentHub Dev"
        $xmlDoc.Save('$(Build.SourcesDirectory)\src\FluentHub.Uwp\Package.appxmanifest')
      failOnStderr: true

  - task: DownloadSecureFile@1
    displayName: 'Download OAuth credentials'
    name: CredentialSecureFile
    inputs:
      secureFile: AppCredentials.config

  - task: CopyFiles@2
    displayName: 'Copy OAuth credentials'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: '$(CredentialSecureFile.secureFilePath)'
      TargetFolder: '$(Build.SourcesDirectory)\src\FluentHub.Uwp'

  - task: DownloadSecureFile@1
    name: caCertificate
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '$(signingCert.secureFilePath)'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    displayName: 'Build FluentHub'
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(buildConfigurationSideload)'
      msbuildArgs: '
      /t:build;_GenerateAppxPackage
      /p:AppInstallerUri="$(build.artifactstagingdirectory)"
      /p:AppxBundlePlatforms="$(buildPlatform)"
      /p:AppxPackageDir="$(appxPackageDir)"
      /p:UapAppxPackageBuildMode=Sideload
      /p:AppxPackageSigningEnabled=true
      /p:PackageCertificateThumbprint=""
      /p:PackageCertificateKeyFile="$(caCertificate.secureFilePath)"
      /p:PackageCertificatePassword="$(signingCert.password)"'

  - task: CopyFiles@2
    displayName: 'Copy generated artifacts'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\$(buildConfigurationSideload)\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'Sideload'

### Store release ###
- job: StoreRelease
  timeoutInMinutes: 40
  steps:
  - task: PowerShell@2
    displayName: 'Canonicalize package manifest'
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\FluentHub.Uwp\Package.appxmanifest
        $xmlDoc.Package.Identity.Name="49462fluenthub-uwp.FluentHub"
        $xmlDoc.Package.Identity.Publisher="CN=4E3C0825-4D00-4ECC-89F8-528E9200B125"
        $xmlDoc.Package.Properties.DisplayName="FluentHub Dev"
        $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="FluentHub Dev"
        $xmlDoc.Save('$(Build.SourcesDirectory)\src\FluentHub.Uwp\Package.appxmanifest')
      failOnStderr: true

  - task: DownloadSecureFile@1
    displayName: 'Download OAuth credentials'
    name: CredentialSecureFile
    inputs:
      secureFile: AppCredentials.config

  - task: CopyFiles@2
    displayName: 'Copy OAuth credentials'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: '$(CredentialSecureFile.secureFilePath)'
      TargetFolder: '$(Build.SourcesDirectory)\src\FluentHub.Uwp'

  - task: DownloadSecureFile@1
    name: caCertificate
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '$(signingCert.secureFilePath)'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    displayName: 'Build FluentHub'
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(buildConfigurationRelease)'
      msbuildArgs: '
      /p:AppInstallerUri="$(build.artifactstagingdirectory)"
      /p:AppxBundlePlatforms="$(buildPlatform)"
      /p:AppxPackageDir="$(appxPackageDir)"
      /p:UapAppxPackageBuildMode=StoreUpload'

  - task: CopyFiles@2
    displayName: 'Copy generated artifacts'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\$(buildConfigurationRelease)\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'StoreUpload'
